version: '3'
services:

  app:
    container_name: node_app
    build: ./nodejs
    ports:
      - 8031:80
    volumes:
      - ./nodejs/app:/usr/src/app
    networks:
      - desafio_2
    depends_on:
      - mysql

  mysql:
    container_name: mysql_desafio_2
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_USER: desafio_2
      MYSQL_PASSWORD: desafio_2
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio_2
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - desafio_2

networks:
  desafio_2:
    driver: bridge